[package]
name = "monkey_lang_rust"
version = "0.1.0"
authors = ["Bradford Lamson-Scribner <brad.lamson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
